import { createApp } from 'vue'
import { createPinia } from 'pinia'
import { createRouter, createWebHistory } from 'vue-router'
// `routes` 는 unplugin-vue-router 가 dev/build 시 자동 생성.
// typecheck 만 단독 실행 시 typed-router.d.ts 가 없어 보일 수 있으나 dev 시 정상.
// @ts-expect-error generated by unplugin-vue-router at build time
import { routes } from 'vue-router/auto-routes'
import { VueQueryPlugin } from '@tanstack/vue-query'

import App from './App.vue'
import { queryClient } from './api/queryClient'
// Sprint c31 / plan/03 §6 — i18n (한국어 1순위 / 영어 2순위).
import { i18n } from './i18n'
import { registerGlobalErrorHandler } from './composables/registerGlobalErrorHandler'
import './styles/main.css'

// Tauri 데스크탑 앱은 SPA 모드로만 동작 (SSR / hydration 없음).
// 라우터는 webHistory + 자동 routes 생성 (unplugin-vue-router).
const router = createRouter({
  history: createWebHistory(),
  routes,
})

const app = createApp(App)

// 전역 uncaught 에러 funnel — toast + Rust tracing sink.
// `app.use(...)` 체인 이전에 등록 — plugin install 단계 에러도 캐치.
// (useToast / i18n.global.t 는 핸들러 호출 시점 lazy resolve 라 안전.)
registerGlobalErrorHandler(app)

app.use(createPinia())
app.use(router)
app.use(VueQueryPlugin, { queryClient })
app.use(i18n)

app.mount('#app')
